// ICode 响应代码
export enum ICode {
  OK = 0,
  FAILED = 1,
  UNKNOWN = 2,

  // STATUS_CONTINUE Continue
  STATUS_CONTINUE = 100,
  STATUS_PROCESSING = 102,

  // STATUS_OK OK
  STATUS_OK = 200,
  STATUS_CREATED = 201,
  STATUS_ACCEPTED = 202,
  STATUS_NO_CONTENT = 204,

  // MULTIPLE_CHOICES MultipleChoices
  STATUS_MULTIPLE_CHOICES = 300,

  // STATUS_BAD_REQUEST Bad Request
  STATUS_BAD_REQUEST = 400,
  STATUS_UNAUTHORIZED = 401,
  STATUS_FORBIDDEN = 403,
  STATUS_NOT_FOUND = 404,
  STATUS_METHOD_NOT_ALLOWED = 405,
  STATUS_REQUEST_TIMEOUT = 408,
  STATUS_TOO_MANY_REQUESTS = 429,

  // STATUS_INTERNAL_SERVER Internal Server Error
  STATUS_INTERNAL_SERVER = 500,
  STATUS_NOT_IMPLEMENTED = 501,
  STATUS_BAD_GATEWAY = 502,
  STATUS_SERVICE_UNAVAILABLE = 503,
  STATUS_GATEWAY_TIMEOUT = 504,
}
